filmbase/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path("", include("films.urls")),
    path("signup/", include("signup.urls")),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

films/urls.py
from django.urls import path
from . import views

app_name = "films"
urlpatterns = [
    path('', views.film_list, name='home'),
    path('countries/', views.country_list, name='country_list'),
    path('countries/<int:id>/', views.country_detail, name='country_detail'),
    path('countries/create/', views.country_create, name='country_create'),
    path('countries/<int:id>/update/',
         views.country_update, name='country_update'),
    path('countries/<int:id>/delete/',
         views.country_delete, name='country_delete'),
    path('countries/autocomplete/',
         views.CountryAutocomplete.as_view(), name='country_autocomplete'),

    path('genres/', views.genre_list, name='genre_list'),
    path('genres/<int:id>/', views.genre_detail, name='genre_detail'),
    path('genres/create/', views.genre_create, name='genre_create'),
    path('genres/<int:id>/update/',
         views.genre_update, name='genre_update'),
    path('genres/<int:id>/delete/',
         views.genre_delete, name='genre_delete'),

    path('films/', views.film_list, name='film_list'),
    path('films/<int:id>/', views.film_detail, name='film_detail'),
    path('films/create/', views.film_create, name='film_create'),
    path('films/<int:id>/update/',
         views.film_update, name='film_update'),
    path('film/<int:id>/delete/',
         views.film_delete, name='film_delete'),

    path('people/', views.person_list, name='person_list'),
    path('people/<int:id>/', views.person_detail, name='person_detail'),
    path('people/create/', views.person_create, name='person_create'),
    path('people/<int:id>/update/',
         views.person_update, name='person_update'),
    path('people/<int:id>/delete/',
         views.person_delete, name='person_delete'),
    path('people/autocomplete/',
         views.PersonAutocomplete.as_view(), name='person_autocomplete'),

    path('awards/', views.award_list, name='award_list'),
    path('awards/<int:id>/', views.award_detail, name='award_detail'),
    path('awards/create/', views.award_create, name='award_create'),
    path('awards/<int:id>/update/', views.award_update, name='award_update'),
    path('awards/<int:id>/delete/', views.award_delete, name='award_delete'),

    path('nominations/', views.nomination_list, name='nomination_list'),
    path('nominations/<int:id>/', views.nomination_detail, name='nomination_detail'),
    path('nominations/create/', views.nomination_create, name='nomination_create'),
    path('nominations/<int:id>/update/', views.nomination_update, name='nomination_update'),
    path('nominations/<int:id>/delete/', views.nomination_delete, name='nomination_delete'),

    path('results/', views.result_list, name='result_list'),
    path('results/<int:id>/', views.result_detail, name='result_detail'),
    path('results/create/', views.result_create, name='result_create'),
    path('results/<int:id>/update/', views.result_update, name='result_update'),
    path('results/<int:id>/delete/', views.result_delete, name='result_delete'),
]

films/forms.py
from django import forms
from dal import autocomplete
from .models import Country, Genre, Film, Person, Award, Nomination, Result


class CountryForm(forms.ModelForm):
    class Meta:
        model = Country
        fields = ['name']


class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ['name']


class FilmForm(forms.ModelForm):
    class Meta:
        model = Film
        fields = ['name', 'origin_name', 'slogan', 'length', 'year',
                  'trailer_url', 'cover', 'description', 'country', 'genres',
                  "director", 'people']
        widgets = {
            'people': autocomplete.ModelSelect2Multiple(
                url='films:person_autocomplete'),
            'director': autocomplete.ModelSelect2(
                url='films:person_autocomplete'),
            'country': autocomplete.ModelSelect2(
                url='films:country_autocomplete'),
        }


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['name', 'origin_name', 'birthday', 'photo']
        widgets = {
            "birthday": forms.DateInput(attrs={'type': 'date'},
                                        format="%Y-%m-%d")
        }

class AwardForm(forms.ModelForm):
    class Meta:
        model = Award
        fields = ['name', 'year']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'year': forms.NumberInput(attrs={'class': 'form-control'}),
        }
    def clean_year(self):
        year = self.cleaned_data.get('year')
        if year < 1900 or year > 2026:
            raise forms.ValidationError("Год должен быть от 1900 до 2026.")
        return year

class NominationForm(forms.ModelForm):
    class Meta:
        model = Nomination
        fields = ['name', 'award']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'award': forms.Select(attrs={'class': 'form-control'}),
        }

class ResultForm(forms.ModelForm):
    class Meta:
        model = Result
        fields = ['nomination', 'person', 'film', 'is_won']
        widgets = {
            'nomination': forms.Select(attrs={'class': 'form-control'}),
            'person': forms.Select(attrs={'class': 'form-control'}),
            'film': forms.Select(attrs={'class': 'form-control'}),
            'is_won': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

films/views.py
from dal import autocomplete
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import user_passes_test
from .models import Country, Film, Genre, Person
from .forms import CountryForm, GenreForm, FilmForm, PersonForm
from .models import Award, Nomination, Result
from .forms import AwardForm, NominationForm, ResultForm
from .helpers import paginate
from django.contrib import messages


def check_admin(user):
    return user.is_superuser


def country_list(request):
    countries = Country.objects.all()
    return render(request, 'films/country/list.html', {'countries': countries})


def country_detail(request, id):
    country = get_object_or_404(Country, id=id)
    films = Film.objects.filter(country=country)

    films = paginate(request, films)
    return render(request, 'films/country/detail.html',
                  {'country': country, 'films': films})


@user_passes_test(check_admin)
def country_create(request):
    if request.method == 'POST':
        form = CountryForm(request.POST)
        if form.is_valid():
            country = form.save()
            messages.success(request, 'Страна добавлена')
            return redirect('films:country_detail', id=country.id)
    else:
        form = CountryForm()
    return render(request, 'films/country/create.html', {'form': form})


@user_passes_test(check_admin)
def country_update(request, id):
    country = get_object_or_404(Country, id=id)
    if request.method == 'POST':
        form = CountryForm(request.POST, instance=country)
        if form.is_valid():
            form.save()
            messages.success(request, 'Страна изменена')
            return redirect('films:country_detail', id=country.id)
    else:
        form = CountryForm(instance=country)
    return render(request, 'films/country/update.html',
                  {'form': form})


@user_passes_test(check_admin)
def country_delete(request, id):
    country = get_object_or_404(Country, id=id)
    if request.method == 'POST':
        country.delete()
        messages.success(request, 'Страна удалена')
        return redirect('films:country_list')
    return render(request, 'films/country/delete.html',
                  {'country': country})


def genre_list(request):
    genres = Genre.objects.all()
    return render(request, 'films/genre/list.html', {'genres': genres})


def genre_detail(request, id):
    genre = get_object_or_404(Genre, id=id)
    films = Film.objects.filter(genres=genre)

    films = paginate(request, films)
    return render(request, 'films/genre/detail.html',
                  {'genre': genre, 'films': films})


@user_passes_test(check_admin)
def genre_create(request):
    if request.method == 'POST':
        form = GenreForm(request.POST)
        if form.is_valid():
            genre = form.save()
            messages.success(request, 'Жанр добавлен')
            return redirect('films:genre_detail', id=genre.id)
    else:
        form = GenreForm()
    return render(request, 'films/genre/create.html', {'form': form})


@user_passes_test(check_admin)
def genre_update(request, id):
    genre = get_object_or_404(Genre, id=id)
    if request.method == 'POST':
        form = GenreForm(request.POST, instance=genre)
        if form.is_valid():
            form.save()
            messages.success(request, 'Жанр изменён')
            return redirect('films:genre_detail', id=genre.id)
    else:
        form = GenreForm(instance=genre)
    return render(request, 'films/genre/update.html',
                  {'form': form})


@user_passes_test(check_admin)
def genre_delete(request, id):
    genre = get_object_or_404(Genre, id=id)
    if request.method == 'POST':
        genre.delete()
        messages.success(request, 'Жанр удалён')
        return redirect('films:genre_list')
    return render(request, 'films/genre/delete.html',
                  {'genre': genre})


def film_list(request):
    films = Film.objects.all()
    query = request.GET.get('query', '')
    if query:
        films = films.filter(name__icontains=query)
    films = paginate(request, films)
    return render(request, 'films/film/list.html', {'films': films,
                                                    'query': query})


def film_detail(request, id):
    queryset = Film.objects.prefetch_related(
        "country", "genres", "director", "people",
        "results__nomination__award"
    )
    film = get_object_or_404(queryset, id=id)
    awards_results = film.results.all()
    return render(request, 'films/film/detail.html',
                  {'film': film, 'awards_results': awards_results})


@user_passes_test(check_admin)
def film_create(request):
    if request.method == 'POST':
        form = FilmForm(request.POST, request.FILES)
        if form.is_valid():
            film = form.save()
            messages.success(request, 'Фильм добавлен')
            return redirect('films:film_detail', id=film.id)
    else:
        form = FilmForm()
    return render(request, 'films/film/create.html', {'form': form})


@user_passes_test(check_admin)
def film_update(request, id):
    film = get_object_or_404(Film, id=id)
    if request.method == 'POST':
        form = FilmForm(request.POST, request.FILES, instance=film)
        if form.is_valid():
            form.save()
            messages.success(request, 'Фильм изменён')
            return redirect('films:film_detail', id=film.id)
    else:
        form = FilmForm(instance=film)
    return render(request, 'films/film/update.html',
                  {'form': form})


@user_passes_test(check_admin)
def film_delete(request, id):
    film = get_object_or_404(Film, id=id)
    if request.method == 'POST':
        film.delete()
        messages.success(request, 'Фильм удалён')
        return redirect('films:film_list')
    return render(request, 'films/film/delete.html',
                  {'film': film})


def person_list(request):
    people = Person.objects.all()
    query = request.GET.get('query', '')
    if query:
        people = people.filter(name__icontains=query)
    people = paginate(request, people)
    return render(request, 'films/person/list.html', {'people': people,
                                                      'query': query})


def person_detail(request, id):
    queryset = Person.objects.prefetch_related(
        "film_set", "directed_films",
        "results__nomination__award"
    )
    person = get_object_or_404(queryset, id=id)
    awards_results = person.results.all()
    return render(request, 'films/person/detail.html',
                  {'person': person, 'awards_results': awards_results})


@user_passes_test(check_admin)
def person_create(request):
    if request.method == 'POST':
        form = PersonForm(request.POST, request.FILES)
        if form.is_valid():
            person = form.save()
            messages.success(request, 'Персона добавлена')
            return redirect('films:person_detail', id=person.id)
    else:
        form = PersonForm()
    return render(request, 'films/person/create.html', {'form': form})


@user_passes_test(check_admin)
def person_update(request, id):
    person = get_object_or_404(Person, id=id)
    if request.method == 'POST':
        form = PersonForm(request.POST, request.FILES, instance=person)
        if form.is_valid():
            form.save()
            messages.success(request, 'Персона изменена')
            return redirect('films:person_detail', id=person.id)
    else:
        form = PersonForm(instance=person)
    return render(request, 'films/person/update.html',
                  {'form': form})


@user_passes_test(check_admin)
def person_delete(request, id):
    person = get_object_or_404(Person, id=id)
    if request.method == 'POST':
        person.delete()
        messages.success(request, 'Персона удалена')
        return redirect('films:person_list')
    return render(request, 'films/person/delete.html',
                  {'person': person})


class PersonAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        people = Person.objects.all()
        if self.q:
            people = people.filter(name__istartswith=self.q)
        return people


class CountryAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        countries = Country.objects.all()
        if self.q:
            countries = countries.filter(name__istartswith=self.q)
        return countries

def award_list(request):
    query = request.GET.get('query', '').strip()
    year_query = request.GET.get('year', '').strip()

    awards = Award.objects.all().order_by('-year', 'name')

    if query:
        awards = awards.filter(name__icontains=query)

    if year_query.isdigit():
        awards = awards.filter(year=int(year_query))

    context = {
        'awards': awards,
        'query': query,
        'year_query': year_query,
    }
    return render(request, 'films/award_list.html', context)

def award_detail(request, id):
    award = get_object_or_404(Award, id=id)
    nominations = Nomination.objects.filter(award=award).prefetch_related('results') # Оптимизация запроса
    return render(request, 'films/award/detail.html', {'award': award, 'nominations': nominations})

@user_passes_test(check_admin)
def award_create(request):
    if request.method == 'POST':
        form = AwardForm(request.POST)
        if form.is_valid():
            award = form.save()
            messages.success(request, 'Премия добавлена')
            return redirect('films:award_detail', id=award.id)
    else:
        form = AwardForm()
    return render(request, 'films/award/create.html', {'form': form})

@user_passes_test(check_admin)
def award_update(request, id):
    award = get_object_or_404(Award, id=id)
    if request.method == 'POST':
        form = AwardForm(request.POST, instance=award)
        if form.is_valid():
            form.save()
            messages.success(request, 'Премия изменена')

films/templates/films/nomination/create.html
{% extends 'films/base.html' %}
{% load django_bootstrap5 %}

{% block title %}Добавить номинацию{% endblock %}

{% block content %}
<h1>Добавить номинацию</h1>

<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='floating' %}
    {% bootstrap_button button_type="submit" content="Сохранить" %}
    <a href="{% url 'films:nomination_list' %}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock %}

films/templates/films/nomination/delete.html
{% extends 'films/base.html' %}

{% block title %}Удалить номинацию "{{ nomination.name }}"{% endblock %}

{% block content %}
<h1>Удалить номинацию "{{ nomination.name }}"?</h1>
<p>Вы уверены, что хотите удалить эту номинацию? Все связанные результаты также будут удалены. Это действие нельзя отменить.</p>

<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Да, удалить</button>
    <a href="{% url 'films:nomination_detail' nomination.id %}" class="btn btn-secondary">Отмена</a>
</form>
{% endblock %}

films/templates/films/nomination/detail.html
{% extends 'films/base.html' %}

{% block title %}{{ nomination.name }} - {{ nomination.award.name }}{% endblock %}

{% block content %}
<h1>{{ nomination.name }}</h1>
<h2>Премия: <a href="{% url 'films:award_detail' nomination.award.id %}">{{ nomination.award.name }} ({{ nomination.award.year }})</a></h2>

<div class="mb-3">
    {% if user.is_superuser %}
        <a href="{% url 'films:nomination_update' nomination.id %}" class="btn btn-outline-secondary me-1">Изменить</a>
        <a href="{% url 'films:nomination_delete' nomination.id %}" class="btn btn-outline-danger">Удалить</a>
    {% endif %}
</div>

<h3>Результаты:</h3>
{% if results %}
    <ul class="list-group">
        {% for result in results %}
            <li class="list-group-item">
                {% if result.is_won %}
                    <strong>Победитель:</strong>
                {% else %}
                    Номинант:
                {% endif %}
                {% if result.person %}
                    <a href="{% url 'films:person_detail' result.person.id %}">{{ result.person.name }}</a>
                {% elif result.film %}
                    <a href="{% url 'films:film_detail' result.film.id %}">{{ result.film.name }}</a>
                {% else %}
                    Неизвестный
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p class="text-muted">Нет результатов для этой номинации.</p>
{% endif %}

{% if user.is_superuser %}
    <a href="{% url 'films:result_create' %}?nomination={{ nomination.id }}" class="btn btn-primary mt-2">Добавить результат</a>
{% endif %}

{% endblock %}

films/templates/films/nomination/list.html
{% extends 'films/base.html' %}

{% block title %}Номинации{% endblock %}

{% block content %}
<h1>Список номинаций</h1>
{% if user.is_superuser %}
    <a href="{% url 'films:nomination_create' %}" class="btn btn-primary mb-3">Добавить номинацию</a>
{% endif %}

<div class="row">
    {% for nomination in nominations %}
        <div class="col-md-6 col-lg-4 mb-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'films:nomination_detail' nomination.id %}">{{ nomination.name }}</a></h5>
                    <p class="card-text">Премия: <a href="{% url 'films:award_detail' nomination.award.id %}">{{ nomination.award.name }} ({{ nomination.award.year }})</a></p>
                    {% if user.is_superuser %}
                        <a href="{% url 'films:nomination_update' nomination.id %}" class="btn btn-sm btn-outline-secondary me-1">Изменить</a>
                        <a href="{% url 'films:nomination_delete' nomination.id %}" class="btn btn-sm btn-outline-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
    {% empty %}
        <p class="text-muted">Нет номинаций.</p>
    {% endfor %}
</div>
{% endblock %}

films/templates/films/nomination/update.html
{% extends 'films/base.html' %}
{% load django_bootstrap5 %}
{% load films_tags %}

{% block breadcrumb %}
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{% url 'films:film_list' %}">{{ 'films:film'|model_verbose_name_plural }}</a>
      </li>
      <li class="breadcrumb-item">
        <a href="{% url 'films:film_detail' form.instance.id %}">{{ form.instance.id }}</a>
      </li>
      <li class="breadcrumb-item active">Редактирование номинации</li>
    </ol>
  </nav>
{% endblock %}
{% block content %}
  <h1>Редактирование номинации</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {{ form.media }}
    {% bootstrap_button button_type='submit' content='Сохранить' %}
  </form>
{% endblock %}